version: '3.9'

services:
  # GATEWAY (Reverse Proxy)
  pickmeup-gateway:
    build:
      context: .
      dockerfile: PickMeUp.Api/Dockerfile
    ports:
      - "5080:8080"
    depends_on:
      - pickmeup-user-api
      - pickmeup-auth-api
      - pickmeup-driver-api
      - pickmeup-ride-api
      - pickmeup-payment-api
      - pickmeup-rating-api
      - pickmeup-notification-api
    environment:
      - ASPNETCORE_URLS=http://+:8080

  # USER API
  pickmeup-user-api:
    build:
      context: .
      dockerfile: UserService/PickMeUp.User.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - Jwt__Secret=9a$R39rJb_#u82z@Ls4!zWpKQh2XpP7h
    depends_on:
      - db

  # AUTH API
  pickmeup-auth-api:
    build:
      context: .
      dockerfile: AuthService/PickMeUp.Auth.API/Dockerfile
    ports:
      - "5002:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080

  # DRIVER API
  pickmeup-driver-api:
    build:
      context: .
      dockerfile: DriverService/PickMeUp.Driver.API/Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080

  # RIDE API
  pickmeup-ride-api:
    build:
      context: .
      dockerfile: RideService/PickMeUp.Ride.API/Dockerfile
    ports:
      - "5004:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080

  # PAYMENT API
  pickmeup-payment-api:
    build:
      context: .
      dockerfile: PaymentService/PickMeUp.Payment.API/Dockerfile
    ports:
      - "5005:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080

  # RATING API
  pickmeup-rating-api:
    build:
      context: .
      dockerfile: RatingService/PickMeUp.Rating.API/Dockerfile
    ports:
      - "5006:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080

  # NOTIFICATION API
  pickmeup-notification-api:
    build:
      context: .
      dockerfile: NotificationService/PickMeUp.Notification.API/Dockerfile
    ports:
      - "5007:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080

  # MSSQL DATABASE
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "QWElkj132!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
